### PR TITLE
Show degen or ens name if any on the profile page

### PR DESCRIPTION
**Pull request by defichopper**
See issue https://github.com/vocdoni/vote-frame/issues/125

The screenshot shows the expected result on the profile page

image

### CODE REVIEW

**Comment by tempe-techie** [comment]
Great job @defichopper 👏

**Comment by tempe-techie** [comment]
@elboletaire Actually Chopper plans to make a few more PRs to fulfill all the tasks in the issue. This is just the first PR, he'll add .degen names in other places too. :)

**Comment by elboletaire** [comment]
> @elboletaire Actually Chopper plans to make a few more PRs to fulfill all the tasks in the issue. This is just the first PR, he'll add .degen names in other places too. :)

That's what we want to avoid.... because adding them in more places, without differentiating them properly, could lead to confusion, like adding people to the muted users list. If we replace names everywhere we would need to also allow using .degen names in the backend, which is the one responsible in this case.

Showing them properly differentiated could avoid part of the confusion, but then I don't think we can show them in every place where a user name is shown, due to space limitations.

I think is ok just having them in the profile for now, but of course we're open to suggestions 😄

**Comment by tempe-techie** [comment]
Ok, whatever you think makes most sense 👍

**Pull request merged**
